In [ ]:
import numpy as np

H, W = map(int, input().split())

M_in = np.zeros((H, W))
M_out = np.zeros((H, W))

row_sum = np.zeros(H)
col_sum = np.zeros(W)

for i in range(H):
    l = np.array(list(map(int, input().split())))
    row_sum[i] = l.sum()
    M_in[i] = l
    col_sum += l

for i in range(H):
    for j in range(W):
        M_out[i][j] = row_sum[i] + col_sum[j] - M_in[i][j]
        

for i in range(H):
    M_out = np.array(M_out, dtype=np.int32)
    print(" ".join(map(str, list(M_out[i]))))

In [55]:
for i in range(H):
    for j in range(W):
        M_out[i][j] = (row_sum[i] + col_sum[j] - M_in[i][j])
        print(row_sum[i], col_sum[j], M_in[i][j], M_out[i][j])

565.0 93.0 31.0 115
565.0 105.0 41.0 117
565.0 92.0 59.0 86
565.0 109.0 26.0 -120
565.0 80.0 53.0 80
565.0 153.0 58.0 -108
565.0 99.0 97.0 55
565.0 181.0 93.0 -115
565.0 64.0 23.0 94
565.0 181.0 84.0 -106
592.0 93.0 62.0 111
592.0 105.0 64.0 121
592.0 92.0 33.0 -117
592.0 109.0 83.0 106
592.0 80.0 27.0 -123
592.0 153.0 95.0 -118
592.0 99.0 2.0 -79
592.0 181.0 88.0 -83
592.0 64.0 41.0 103
592.0 181.0 97.0 -92


In [58]:
M_out[0][0] = 512

In [59]:
M_out

array([[   0,  117,   86, -120,   80, -108,   55, -115,   94, -106],
       [ 111,  121, -117,  106, -123, -118,  -79,  -83,  103,  -92]],
      dtype=int8)

In [23]:
col_sum_list

array([3., 3., 3.])

In [28]:
a[0][:]

array([0., 0., 0., 0.])

In [74]:
H, W = map(int, input().split())
A = [[int(d) for d in input().split()] for _ in range(H)]
# A = []
# for i in range(H):
#     A.append([int(d) for d in input().split()])
rows = [sum(a) for a in A]
cols = [sum(z) for z in zip(*A)]


for y, row in enumerate(A):
    print(' '.join(str(rows[y] + cols[x] - A[y][x]) for x, v in enumerate(row)))

 3 3
 1 1 1
 1 1 1
 1 1 1


5 5 5
5 5 5
5 5 5
