In [13]:
import torch

In [19]:
%%time
a = torch.ones(3000, 3000).cuda()
b = torch.ones(3000, 3000).cuda()

CPU times: user 119 ms, sys: 138 ms, total: 257 ms
Wall time: 22.7 ms


In [20]:
%%time
torch.matmul(a, b)

CPU times: user 1.41 ms, sys: 851 µs, total: 2.27 ms
Wall time: 1.06 ms


tensor([[3000., 3000., 3000.,  ..., 3000., 3000., 3000.],
        [3000., 3000., 3000.,  ..., 3000., 3000., 3000.],
        [3000., 3000., 3000.,  ..., 3000., 3000., 3000.],
        ...,
        [3000., 3000., 3000.,  ..., 3000., 3000., 3000.],
        [3000., 3000., 3000.,  ..., 3000., 3000., 3000.],
        [3000., 3000., 3000.,  ..., 3000., 3000., 3000.]], device='cuda:0')

In [10]:
a = torch.ones(3000, 3000)
b = torch.ones(3000, 3000)

In [14]:
import numpy as np

In [15]:
a = np.ones((3000, 3000))
b = np.ones((3000, 3000))

In [18]:
%%time
np.matmul(a, b)

CPU times: user 4.65 s, sys: 1.75 s, total: 6.39 s
Wall time: 161 ms


array([[3000., 3000., 3000., ..., 3000., 3000., 3000.],
       [3000., 3000., 3000., ..., 3000., 3000., 3000.],
       [3000., 3000., 3000., ..., 3000., 3000., 3000.],
       ...,
       [3000., 3000., 3000., ..., 3000., 3000., 3000.],
       [3000., 3000., 3000., ..., 3000., 3000., 3000.],
       [3000., 3000., 3000., ..., 3000., 3000., 3000.]])

In [1]:
a = 1

In [4]:
a == 0 or 2 or 3

2

In [5]:
a

1

In [10]:
b = [0,2,3]

In [9]:
a in b

False

In [11]:
b[-1]

3

In [17]:
a.shape

(3000, 3000)

In [24]:
img_list = []
img_list.append([a,a,a])

In [25]:
np.array(img_list).shape

(1, 3, 3000, 3000)

In [27]:
x = np.zeros((512, 3, 70, 70))

In [29]:
x[0][0].shape

(70, 70)

In [30]:
a = [0,1,2]

False

In [32]:
a = ["a", "b", "c"]
np.array(a)

array(['a', 'b', 'c'], dtype='<U1')

In [33]:
a = [1,2,3,4,5]
b = [6,7,8,9,10]
c = ["a","b","c","d","e"]

a = np.array(a)
b = np.array(b)
c = np.array(c)

a = a.reshape([5,1])
b = b.reshape([5,1])
c = c.reshape([5,1])

In [43]:
concat = np.concatenate([a,b], 1)

In [47]:
concat[0]

array([1, 6])

In [45]:
import pandas as pd

In [56]:
pd.DataFrame(concat, index=c)

0   1
a  1   6
b  2   7
c  3   8
d  4   9
e  5  10

In [50]:
c = pd.DataFrame(c)

In [51]:
c

0
0  a
1  b
2  c
3  d
4  e

In [55]:
c = ["a","b","c","d","e"]


In [62]:
a: str = "a"

In [63]:
type(a)

str

In [64]:
a

'a'

In [1]:
a=None

In [2]:
a